services:
  - type: web
    name: plain-language-backend
    env: docker # Specify Docker environment
    plan: free
    region: oregon
    # buildCommand and startCommand are not needed for Docker, as they are defined in the Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
  - type: web
    name: plain-language-frontend
    env: python
    plan: free
    region: oregon
    startCommand: "uvicorn services.api.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src/src
